# Generated by Django 3.2.16 on 2023-03-07 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_by', models.CharField(max_length=40)),
                ('device_type', models.CharField(max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=20, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('assigned_device', models.CharField(default='NotAssigned', max_length=50)),
            ],
            options={
                'verbose_name': 'Add_Request',
                'verbose_name_plural': 'Add_Requests',
            },
        ),
        migrations.CreateModel(
            name='device_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('isp', models.CharField(max_length=25)),
                ('data_limit', models.CharField(max_length=25)),
                ('manufacturer', models.CharField(max_length=25)),
                ('device_model', models.CharField(max_length=20)),
                ('imei', models.CharField(max_length=25)),
                ('msisdn', models.CharField(max_length=25)),
                ('sim_card', models.CharField(max_length=30)),
                ('instock_date', models.DateTimeField(auto_now_add=True)),
                ('punched_by', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=200)),
                ('device_status', models.CharField(default='NotAssigned', max_length=50)),
            ],
            options={
                'verbose_name': 'device_inventory',
                'verbose_name_plural': 'device_inventory',
                'db_table': 'device_inventory',
            },
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('isp', models.CharField(max_length=25)),
                ('data_limit', models.CharField(max_length=25)),
                ('manufacturer', models.CharField(max_length=25)),
                ('device_model', models.CharField(max_length=20)),
                ('imei', models.CharField(max_length=25)),
                ('msisdn', models.CharField(max_length=25)),
                ('sim_card', models.CharField(max_length=30)),
                ('device_status', models.CharField(max_length=25)),
                ('remarks', models.CharField(max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device_inventory')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'device_history',
                'verbose_name_plural': 'device_history',
                'db_table': 'device_history',
            },
        ),
    ]
