# Generated by Django 3.2.16 on 2023-02-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('isp', models.CharField(max_length=20)),
                ('data_limit', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('device_model', models.CharField(max_length=20)),
                ('imei', models.IntegerField()),
                ('msisdn', models.IntegerField()),
                ('sim_card', models.CharField(max_length=30)),
                ('device_status', models.CharField(max_length=20)),
                ('device_picture', models.CharField(max_length=30)),
                ('instock_date', models.DateTimeField(auto_now_add=True)),
                ('punched_by', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'device_inventory',
                'verbose_name_plural': 'device_inventory',
                'db_table': 'device_inventory',
            },
        ),
    ]
