# Generated by Django 3.2.16 on 2023-03-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_addrequest_assigned_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_inventory',
            name='status',
            field=models.CharField(default='NotAssigned', max_length=50),
        ),
        migrations.AlterField(
            model_name='addrequest',
            name='assigned_device',
            field=models.CharField(default='NotAssigned', max_length=50),
        ),
        migrations.AlterField(
            model_name='device_inventory',
            name='device_status',
            field=models.CharField(max_length=25),
        ),
    ]
