# Generated by Django 3.2.16 on 2023-02-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_device_inventory_device_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_inventory',
            name='data_limit',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='device_inventory',
            name='device_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='device_inventory',
            name='imei',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='device_inventory',
            name='isp',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='device_inventory',
            name='location',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='device_inventory',
            name='manufacturer',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='device_inventory',
            name='msisdn',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='device_inventory',
            name='type',
            field=models.CharField(max_length=25),
        ),
    ]
