# Generated by Django 3.2.16 on 2023-03-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230307_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrequest',
            name='assigned_device',
        ),
        migrations.AddField(
            model_name='addrequest',
            name='assigned_device_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
