# Generated by Django 3.2.16 on 2023-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230215_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_inventory',
            name='remarks',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
