# Generated by Django 3.2.16 on 2023-03-08 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230308_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrequest',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
