# Generated by Django 3.2.16 on 2023-02-22 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_device_inventory_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('isp', models.CharField(max_length=25)),
                ('data_limit', models.CharField(max_length=25)),
                ('manufacturer', models.CharField(max_length=25)),
                ('device_model', models.CharField(max_length=20)),
                ('imei', models.CharField(max_length=25)),
                ('msisdn', models.CharField(max_length=25)),
                ('sim_card', models.CharField(max_length=30)),
                ('device_status', models.CharField(max_length=25)),
                ('remarks', models.CharField(max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device_inventory')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'device_history',
                'verbose_name_plural': 'device_history',
                'db_table': 'device_history',
            },
        ),
    ]
