# Generated by Django 3.2.16 on 2023-03-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230308_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceallocation',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
