# Generated by Django 3.2.16 on 2023-02-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_addrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addrequest',
            options={'verbose_name': 'Add_Request', 'verbose_name_plural': 'Add_Requests'},
        ),
    ]
