# Generated by Django 3.2.16 on 2023-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_ticket_id_deviceallocation_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='sim_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=25)),
                ('sim_card', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=25)),
                ('isp', models.CharField(max_length=25)),
                ('data_limit', models.CharField(max_length=25)),
                ('instock_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(max_length=20)),
                ('sim_status', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'sim_inventory',
                'verbose_name_plural': 'sim_inventory',
                'db_table': 'sim_inventory',
            },
        ),
        migrations.RemoveField(
            model_name='device_inventory',
            name='msisdn',
        ),
        migrations.RemoveField(
            model_name='device_inventory',
            name='sim_card',
        ),
    ]
