# Generated by Django 3.2.16 on 2023-02-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_addrequest_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrequest',
            old_name='text',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='addrequest',
            name='approved_by',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addrequest',
            name='request_by',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
