# Generated by Django 3.2.16 on 2023-02-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230224_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrequest',
            name='approved_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
