# Generated by Django 3.2.16 on 2023-03-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230309_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrequest',
            old_name='device_type',
            new_name='isp',
        ),
        migrations.AddField(
            model_name='deviceallocation',
            name='assigned_sim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.sim_inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceallocation',
            name='remarks',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
