# Generated by Django 3.2.16 on 2023-03-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230310_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrequest',
            old_name='assigned_device_id',
            new_name='assigned_device_imei',
        ),
        migrations.AddField(
            model_name='device_inventory',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sim_inventory',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sim_inventory',
            name='status',
            field=models.CharField(default='NotAssigned', max_length=50),
        ),
    ]
