# Generated by Django 3.2.16 on 2023-02-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_addrequest_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrequest',
            old_name='user_id',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='addrequest',
            old_name='user_name',
            new_name='name',
        ),
    ]
