# Generated by Django 3.2.16 on 2023-04-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230310_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrequest',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='addrequest',
            name='number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
