# Generated by Django 3.2.16 on 2023-02-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230228_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrequest',
            name='request_by',
            field=models.CharField(max_length=40),
        ),
    ]
