# Generated by Django 3.2.16 on 2023-04-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20230404_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrequest',
            name='cnic',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='addrequest',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
