# Generated by Django 3.2.16 on 2023-04-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230404_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrequest',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addrequest',
            name='designation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addrequest',
            name='entity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addrequest',
            name='location',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='deviceallocation',
            name='criteria',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addrequest',
            name='cnic',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addrequest',
            name='number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
